server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: "uX9z!gA6!Pz5@lFmZrU#oWxTqVeYkPnBvDeFgHiJkLmNoQrStUvWxYz1234567890"
  expiration: 86400000   #1 day
